Aim: To understand the Google Colab environment & implement basic vector addition & matrix multiplication using Python & Numpy

In [2]:
import numpy as np

vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

vector_sum = vector1 + vector2

print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Vector Sum:", vector_sum)


Vector 1: [1 2 3]
Vector 2: [4 5 6]
Vector Sum: [5 7 9]


In [ ]:
matrix1 = np.array([[1, 2, 3], [4, 5, 6]])
matrix2 = np.array([[7, 8], [9, 1], [2, 3]])

matrix_product = np.dot(matrix1, matrix2)

print("\nMatrix 1:\n", matrix1)
print("Matrix 2:\n", matrix2)
print("Matrix Product:\n", matrix_product)


Matrix 1:
 [[1 2 3]
 [4 5 6]]
Matrix 2:
 [[7 8]
 [9 1]
 [2 3]]
Matrix Product:
 [[31 19]
 [85 55]]
